export const sampleBooks = [
  {
    _id: 'sample-1',
    title: 'Introduction to Algorithms',
    authors: ['Thomas H. Cormen'],
    category: 'Computer Science',
    description: 'A foundational reference for algorithm design, analysis, and problem solving.',
    isbn: '9780262046305',
    publisher: 'MIT Press',
    language: 'English',
    shelfLocation: 'CS-A12',
    totalCopies: 8,
    availableCopies: 3,
    featured: true,
    averageRating: 4.8,
    reviewCount: 124
  },
  {
    _id: 'sample-2',
    title: 'Operating System Concepts',
    authors: ['Abraham Silberschatz', 'Peter B. Galvin'],
    category: 'Computer Science',
    description: 'A widely used text covering core operating system design principles and process management.',
    isbn: '9781119800361',
    publisher: 'Wiley',
    language: 'English',
    shelfLocation: 'CS-B05',
    totalCopies: 6,
    availableCopies: 0,
    featured: true,
    averageRating: 4.5,
    reviewCount: 89
  },
  {
    _id: 'sample-3',
    title: 'Modern Physics',
    authors: ['Kenneth S. Krane'],
    category: 'Physics',
    description: 'An accessible guide to relativity, quantum mechanics, and nuclear physics.',
    isbn: '9781118061145',
    publisher: 'Wiley',
    language: 'English',
    shelfLocation: 'PH-C18',
    totalCopies: 5,
    availableCopies: 2,
    featured: false,
    averageRating: 4.3,
    reviewCount: 41
  },
  {
    _id: 'sample-4',
    title: 'Discrete Mathematics and Its Applications',
    authors: ['Kenneth H. Rosen'],
    category: 'Mathematics',
    description: 'Essential coverage of logic, proofs, sets, relations, graphs, and combinatorics.',
    isbn: '9780073383095',
    publisher: 'McGraw-Hill',
    language: 'English',
    shelfLocation: 'MA-D09',
    totalCopies: 9,
    availableCopies: 4,
    featured: true,
    averageRating: 4.6,
    reviewCount: 73
  },
  {
    _id: 'sample-5',
    title: 'History of South Asia',
    authors: ['Barbara D. Metcalf'],
    category: 'History',
    description: 'A survey of key historical developments across South Asia.',
    isbn: '9780521863629',
    publisher: 'Cambridge University Press',
    language: 'English',
    shelfLocation: 'HI-E03',
    totalCopies: 4,
    availableCopies: 1,
    featured: false,
    averageRating: 4.2,
    reviewCount: 26
  },
  {
    _id: 'sample-6',
    title: 'Digital Electronics',
    authors: ['M. Morris Mano'],
    category: 'Electronics',
    description: 'Covers combinational logic, sequential circuits, and digital system fundamentals.',
    isbn: '9789332575776',
    publisher: 'Pearson',
    language: 'English',
    shelfLocation: 'EC-F11',
    totalCopies: 7,
    availableCopies: 2,
    featured: false,
    averageRating: 4.4,
    reviewCount: 58
  }
];

export const sampleCatalogStats = {
  booksInCatalog: 12480,
  availableCopies: 6840,
  activeReservations: 312,
  dueThisWeek: 186
};
